### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/dmitry-ivanov/laravel-console-mutex/pull/26/commits/2387b6fc8df1704641bbe0f5dc1d2e268bb0ec03?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-console-mutex.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "illuminated/console-mutex": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by jerryklimcik** [comment]
Hi @dmitry-ivanov  , may I ask to merge this PR? There shouldn't be any break changes 👍

**Comment by dmitry-ivanov** [comment]
Hi, @jerryklimcik ! I'll take a look at it soon, when I'll have a bit more time. Thanks!

**Comment by dmitry-ivanov** [comment]
@jerryklimcik I've just released the [`9.0.0`](https://github.com/dmitry-ivanov/laravel-console-mutex/releases/tag/9.0.0) with Laravel 9 support 👌

**Pull request closed without merging**
