### PR TITLE
WIP: Upgrade to Laravel 8.x

### LINKED ISSUE #20: Laravel 8
### Follow these steps:

> Please, note that we have to update versions for everything, not only `illuminate` packages.

1. Update versions in `composer.json` according to Laravel's `composer.json`.
2. Add the newly supported version to `README.md`.
3. Open PR to the `master` branch.

### PR DESCRIPTION
**Pull request by mihan007**
Closes #20 

Waiting for accept https://github.com/dmitry-ivanov/laravel-testing-tools/pull/4

### CODE REVIEW

**Comment by mihan007** [comment]
@dmitry-ivanov to get it done please make illuminated/testing-tools:8.0 to avoid
```
"illuminated/testing-tools": "dev-master"
```
see https://github.com/dmitry-ivanov/laravel-console-mutex/pull/21/commits/ec4c0e1400cef049583d2ce33ddac6a88aa1eebf#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R25

**Comment by dmitry-ivanov** [comment]
@mihan007 Yep, I remember about that. I'm still working on some additional fixes for `8.x` of the `testing-tools`.

**Comment by dmitry-ivanov** [comment]
@mihan007 The `8.0.0` has been released for the `testing-tools`, so we can make a final tweak and move PR from the "Draft" state 👍

**Comment by dmitry-ivanov** [comment]
@mihan007 I'll fix it in the `master`, thanks 👍

**Pull request merged**
